export default {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  GET_TODO_LIST_REQUEST: 'GET_TODO_LIST_REQUEST',
  GET_TODO_LIST_SUCCESS: 'GET_TODO_LIST_SUCCESS',
  GET_TODO_LIST_FAILURE: 'GET_TODO_LIST_FAILURE',
};
