export default {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  GET_TODO_LIST_REQUEST: 'GET_TODO_LIST_REQUEST',
  GET_TODO_LIST_SUCCESS: 'GET_TODO_LIST_SUCCESS',
  GET_TODO_LIST_FAILURE: 'GET_TODO_LIST_FAILURE',

  POST_TODO_LIST_REQUEST: 'POST_TODO_LIST_REQUEST',
  POST_TODO_LIST_SUCCESS: 'POST_TODO_LIST_SUCCESS',
  POST_TODO_LIST_FAILURE: 'POST_TODO_LIST_FAILURE',

  PATCH_TODO_LIST_REQUEST: 'PATCH_TODO_LIST_REQUEST',
  PATCH_TODO_LIST_SUCCESS: 'PATCH_TODO_LIST_SUCCESS',
  PATCH_TODO_LIST_FAILURE: 'PATCH_TODO_LIST_FAILURE',

  DELETE_TODO_LIST_REQUEST: 'DELETE_TODO_LIST_REQUEST',
  DELETE_TODO_LIST_SUCCESS: 'DELETE_TODO_LIST_SUCCESS',
  DELETE_TODO_LIST_FAILURE: 'DELETE_TODO_LIST_FAILURE',
};
